REVOKE ALL ON SCHEMA crm FROM PUBLIC;

GRANT USAGE ON SCHEMA crm TO crm_app_rw;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA crm TO crm_app_rw;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA crm TO crm_app_rw;

ALTER DEFAULT PRIVILEGES IN SCHEMA crm
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO crm_app_rw;
ALTER DEFAULT PRIVILEGES IN SCHEMA crm
    GRANT USAGE, SELECT ON SEQUENCES TO crm_app_rw;
